<html>
<head><meta charset="utf-8"><title>wasmtime / PR #1242 Yanix now returns io::Error directly · git-wasmtime · Zulip Chat Archive</title></head>
<h2>Stream: <a href="https://bytecodealliance.github.io/zulip-archive/stream/225357-git-wasmtime/index.html">git-wasmtime</a></h2>
<h3>Topic: <a href="https://bytecodealliance.github.io/zulip-archive/stream/225357-git-wasmtime/topic/wasmtime.20.2F.20PR.20.231242.20Yanix.20now.20returns.20io.3A.3AError.20directly.html">wasmtime / PR #1242 Yanix now returns io::Error directly</a></h3>

<hr>

<base href="https://bytecodealliance.zulipchat.com">

<head><link href="https://bytecodealliance.github.io/zulip-archive/style.css" rel="stylesheet"></head>

<a name="189890458"></a>
<h4><a href="https://bytecodealliance.zulipchat.com#narrow/stream/225357-git-wasmtime/topic/wasmtime%20/%20PR%20%231242%20Yanix%20now%20returns%20io%3A%3AError%20directly/near/189890458" class="zl"><img src="https://bytecodealliance.github.io/zulip-archive/assets/img/zulip.svg" alt="view this post on Zulip" style="width:20px;height:20px;"></a> Wasmtime GitHub notifications bot <a href="https://bytecodealliance.github.io/zulip-archive/stream/225357-git-wasmtime/topic/wasmtime.20.2F.20PR.20.231242.20Yanix.20now.20returns.20io.3A.3AError.20directly.html#189890458">(Mar 06 2020 at 13:06)</a>:</h4>
<p>kubkon edited <a href="https://github.com/bytecodealliance/wasmtime/pull/1242" target="_blank" title="https://github.com/bytecodealliance/wasmtime/pull/1242">PR #1242</a> from <code>yanix-io-error</code> to <code>master</code>:</p>
<blockquote>
<p>This PR may seem somewhat controversial at first, but hear me<br>
out first. Currently, Yanix would return a custom error that's a<br>
wrapper around three other error types returned by various entities<br>
inside Rust's <code>libstd</code>. In particular, Yanix's error type would wrap<br>
<code>io::Error</code>, <code>num::TryFromIntError</code> and <code>ffi::NulError</code>. It turns<br>
out that there is a natural conversion between the first and the last<br>
and provided by the standard library, i.e., <code>From&lt;ffi::NulError&gt; for io::Error</code><br>
is provided. So at the surface it may seem that only the first two<br>
wrapped error types are worth keeping.</p>
<p>Digging a little bit deeper into <code>libstd</code>, <code>num::TryFromIntError</code><br>
is essentially speaking only a marker that the integral conversion<br>
went wrong. The struct implementing this error stores a unit type,<br>
and nothing more. It therefore seems like a waste to wrap this<br>
particular error when we could unify everything under <code>io::Error</code>.<br>
And so, whenever we perform an int conversion, I suggest we simply<br>
remap the error to <code>io::Error::from_raw_os_error(libc::EOVERFLOW)</code><br>
since this carries a comparable amount of information.</p>
<p>As a result of completely discarding <code>yanix::Error</code> custom error type,<br>
we are invariably simplifying <code>yanix</code> itself, but also allowing<br>
<code>wasi-common</code> to simplify in several places as well.</p>
<p>I'm curious to see what you guys reckon!</p>
</blockquote>



<hr><p>Last updated: Jan 20 2025 at 06:04 UTC</p>
</html>