[
    {
        "content": "<p>alexcrichton <a href=\"https://github.com/bytecodealliance/wasmtime/pull/7138#issuecomment-1745568743\">commented</a> on <a href=\"https://github.com/bytecodealliance/wasmtime/pull/7138\">issue #7138</a>:</p>\n<blockquote>\n<p>This was not successful as <a href=\"https://github.com/bytecodealliance/wasmtime/actions/runs/6396857346\">this failure</a> indicates. That failure is a commit based on the merge of this PR, and the same test failed. I will keep investigating.</p>\n</blockquote>",
        "id": 394694416,
        "sender_full_name": "Wasmtime GitHub notifications bot",
        "timestamp": 1696360359
    },
    {
        "content": "<p>alexcrichton <a href=\"https://github.com/bytecodealliance/wasmtime/pull/7138#issuecomment-1745596592\">commented</a> on <a href=\"https://github.com/bytecodealliance/wasmtime/pull/7138\">issue #7138</a>:</p>\n<blockquote>\n<p>Ok I think I found the real cause in <a href=\"https://github.com/bytecodealliance/wasmtime/pull/7144\">https://github.com/bytecodealliance/wasmtime/pull/7144</a></p>\n</blockquote>",
        "id": 394697061,
        "sender_full_name": "Wasmtime GitHub notifications bot",
        "timestamp": 1696361538
    }
]