[
    {
        "content": "<p>kubkon <a href=\"https://github.com/bytecodealliance/wasmtime/pull/1253#issuecomment-596597905\" target=\"_blank\" title=\"https://github.com/bytecodealliance/wasmtime/pull/1253#issuecomment-596597905\">commented</a> on <a href=\"https://github.com/bytecodealliance/wasmtime/pull/1253\" target=\"_blank\" title=\"https://github.com/bytecodealliance/wasmtime/pull/1253\">Issue #1253</a>:</p>\n<blockquote>\n<p>All prereqs met, so we're ready to go!</p>\n</blockquote>",
        "id": 190080685,
        "sender_full_name": "Wasmtime GitHub notifications bot",
        "timestamp": 1583767490
    },
    {
        "content": "<p>kubkon <a href=\"https://github.com/bytecodealliance/wasmtime/pull/1253#issuecomment-596642053\" target=\"_blank\" title=\"https://github.com/bytecodealliance/wasmtime/pull/1253#issuecomment-596642053\">commented</a> on <a href=\"https://github.com/bytecodealliance/wasmtime/pull/1253\" target=\"_blank\" title=\"https://github.com/bytecodealliance/wasmtime/pull/1253\">Issue #1253</a>:</p>\n<blockquote>\n<p>As far as CI failures are concerned, <a href=\"https://www.githubstatus.com/\" target=\"_blank\" title=\"https://www.githubstatus.com/\">Github</a> is experiencing some issues right now and I think that's the reason. I cannot see how this PR could have broken the CI otherwise <span aria-label=\"thinking\" class=\"emoji emoji-1f914\" role=\"img\" title=\"thinking\">:thinking:</span> </p>\n</blockquote>",
        "id": 190090012,
        "sender_full_name": "Wasmtime GitHub notifications bot",
        "timestamp": 1583772077
    }
]