[
    {
        "content": "<p><span class=\"user-mention\" data-user-id=\"254083\">@Dan Gohman</span> hm looks like this build failed on master -- <a href=\"https://github.com/bytecodealliance/wasmtime/runs/501673516?check_suite_focus=true\" target=\"_blank\" title=\"https://github.com/bytecodealliance/wasmtime/runs/501673516?check_suite_focus=true\">https://github.com/bytecodealliance/wasmtime/runs/501673516?check_suite_focus=true</a> -- which I think is the test you added</p>\n<div class=\"message_embed\"><a class=\"message_embed_image\" href=\"https://github.com/bytecodealliance/wasmtime/runs/501673516?check_suite_focus=true\" style=\"background-image: url(https://avatars0.githubusercontent.com/u/54038801?s=400&amp;v=4)\" target=\"_blank\"></a><div class=\"data-container\"><div class=\"message_embed_title\"><a href=\"https://github.com/bytecodealliance/wasmtime/runs/501673516?check_suite_focus=true\" target=\"_blank\" title=\"bytecodealliance/wasmtime\">bytecodealliance/wasmtime</a></div><div class=\"message_embed_description\">Standalone JIT-style runtime for WebAssembly, using Cranelift - bytecodealliance/wasmtime</div></div></div>",
        "id": 190332134,
        "sender_full_name": "Alex Crichton",
        "timestamp": 1583961147
    },
    {
        "content": "<p>is that a spurious failure you think?</p>",
        "id": 190332146,
        "sender_full_name": "Alex Crichton",
        "timestamp": 1583961155
    },
    {
        "content": "<p>It failed once in the CI on the PR, but then after I started debugging it, it disappeared and started passing.</p>",
        "id": 190332210,
        "sender_full_name": "Dan Gohman",
        "timestamp": 1583961211
    },
    {
        "content": "<p>It looks like the child wasmtime process is failing with a SIGSEGV before printing anything.</p>",
        "id": 190332295,
        "sender_full_name": "Dan Gohman",
        "timestamp": 1583961250
    },
    {
        "content": "<p>oh dear, sounds like a spurious error then</p>",
        "id": 190332312,
        "sender_full_name": "Alex Crichton",
        "timestamp": 1583961261
    },
    {
        "content": "<p>I will try to reproduce</p>",
        "id": 190332336,
        "sender_full_name": "Alex Crichton",
        "timestamp": 1583961272
    },
    {
        "content": "<p>It doesn't reproduce for me at all locally; i've only seen it fail in CI</p>",
        "id": 190333140,
        "sender_full_name": "Dan Gohman",
        "timestamp": 1583961735
    },
    {
        "content": "<p>managed to get a reliable reproduction - <a href=\"https://github.com/bytecodealliance/wasmtime/issues/1295\" target=\"_blank\" title=\"https://github.com/bytecodealliance/wasmtime/issues/1295\">https://github.com/bytecodealliance/wasmtime/issues/1295</a></p>\n<div class=\"message_embed\"><a class=\"message_embed_image\" href=\"https://github.com/bytecodealliance/wasmtime/issues/1295\" style=\"background-image: url(https://avatars0.githubusercontent.com/u/54038801?s=400&amp;v=4)\" target=\"_blank\"></a><div class=\"data-container\"><div class=\"message_embed_title\"><a href=\"https://github.com/bytecodealliance/wasmtime/issues/1295\" target=\"_blank\" title=\"Spurious segfault when generating a backtrace on a trap 路 Issue #1295 路 bytecodealliance/wasmtime\">Spurious segfault when generating a backtrace on a trap 路 Issue #1295 路 bytecodealliance/wasmtime</a></div><div class=\"message_embed_description\">Investigating a spurious test failure I&#39;m able to reproduce this locally on Linux with a script that looks like this: use std::os::unix::prelude::*; use std::process::Command; fn main() { let s...</div></div></div>",
        "id": 190333600,
        "sender_full_name": "Alex Crichton",
        "timestamp": 1583962063
    },
    {
        "content": "<p>I couldn't see it locally either until I ran a bunch in parallel</p>",
        "id": 190333612,
        "sender_full_name": "Alex Crichton",
        "timestamp": 1583962073
    },
    {
        "content": "<p>for what may be unrelated reasons CI is failing a lot right now</p>",
        "id": 190417888,
        "sender_full_name": "Alex Crichton",
        "timestamp": 1584033726
    },
    {
        "content": "<p>and github is sort of refusing to give me any logs</p>",
        "id": 190417900,
        "sender_full_name": "Alex Crichton",
        "timestamp": 1584033734
    },
    {
        "content": "<p>I'm at a bit of a loss as to what's going on</p>",
        "id": 190417907,
        "sender_full_name": "Alex Crichton",
        "timestamp": 1584033739
    },
    {
        "content": "<p>I was seeing the same logs issue, but you can still view raw logs, fwiw</p>",
        "id": 190419671,
        "sender_full_name": "fitzgen (he/him)",
        "timestamp": 1584034529
    },
    {
        "content": "<p><span class=\"user-mention\" data-user-id=\"253994\">@Alex Crichton</span></p>",
        "id": 190419682,
        "sender_full_name": "fitzgen (he/him)",
        "timestamp": 1584034535
    },
    {
        "content": "<p>oh nice</p>",
        "id": 190420170,
        "sender_full_name": "Alex Crichton",
        "timestamp": 1584034737
    }
]