[
    {
        "content": "<p>Is it a bug in rust that it lets me call <code>eprintln</code> in the <code>drop</code> of a <code>thread_local</code> object, but it crashes at runtime?</p>",
        "id": 190426073,
        "sender_full_name": "Dan Gohman",
        "timestamp": 1584037252
    },
    {
        "content": "<p><a href=\"https://play.rust-lang.org/?version=stable&amp;mode=debug&amp;edition=2018&amp;gist=f149db03011ee75509935043af8cb3db\" target=\"_blank\" title=\"https://play.rust-lang.org/?version=stable&amp;mode=debug&amp;edition=2018&amp;gist=f149db03011ee75509935043af8cb3db\">https://play.rust-lang.org/?version=stable&amp;mode=debug&amp;edition=2018&amp;gist=f149db03011ee75509935043af8cb3db</a></p>",
        "id": 190426081,
        "sender_full_name": "Dan Gohman",
        "timestamp": 1584037256
    },
    {
        "content": "<p><span class=\"user-mention\" data-user-id=\"253994\">@Alex Crichton</span> ^ -- working on porting my sigaltstack code from C++ to Rust and hitting this error</p>",
        "id": 190426160,
        "sender_full_name": "Dan Gohman",
        "timestamp": 1584037313
    },
    {
        "content": "<p><span class=\"user-mention\" data-user-id=\"254083\">@Dan Gohman</span> its definitely dubious yeah, although not necessarily a bug</p>",
        "id": 190426344,
        "sender_full_name": "Alex Crichton",
        "timestamp": 1584037436
    },
    {
        "content": "<p>Dtors in tls run in an extremely limited context</p>",
        "id": 190426401,
        "sender_full_name": "Alex Crichton",
        "timestamp": 1584037449
    },
    {
        "content": "<p>But we probably should panic in linstd</p>",
        "id": 190426409,
        "sender_full_name": "Alex Crichton",
        "timestamp": 1584037458
    },
    {
        "content": "<p>hm no this is definitely a bug</p>",
        "id": 190427074,
        "sender_full_name": "Alex Crichton",
        "timestamp": 1584037890
    },
    {
        "content": "<p>I'll dig in</p>",
        "id": 190427079,
        "sender_full_name": "Alex Crichton",
        "timestamp": 1584037891
    },
    {
        "content": "<p>It looks like it definitely is the eprintln, which I was only using for debugging, so I have a workaround, which is to not use eprintln :-}</p>",
        "id": 190427982,
        "sender_full_name": "Dan Gohman",
        "timestamp": 1584038401
    },
    {
        "content": "<p><span class=\"user-mention\" data-user-id=\"254083\">@Dan Gohman</span> <a href=\"https://github.com/rust-lang/rust/pull/69955\" target=\"_blank\" title=\"https://github.com/rust-lang/rust/pull/69955\">https://github.com/rust-lang/rust/pull/69955</a></p>\n<div class=\"message_embed\"><a class=\"message_embed_image\" href=\"https://github.com/rust-lang/rust/pull/69955\" style=\"background-image: url(https://avatars1.githubusercontent.com/u/5430905?s=400&amp;v=4)\" target=\"_blank\"></a><div class=\"data-container\"><div class=\"message_embed_title\"><a href=\"https://github.com/rust-lang/rust/pull/69955\" target=\"_blank\" title=\"Fix abort-on-eprintln during process shutdown by alexcrichton 路 Pull Request #69955 路 rust-lang/rust\">Fix abort-on-eprintln during process shutdown by alexcrichton 路 Pull Request #69955 路 rust-lang/rust</a></div><div class=\"message_embed_description\">This commit fixes an issue where if eprintln! is used in a TLS\ndestructor it can accidentally cause the process to abort. TLS\ndestructors are executed after main returns on the main thread, and at\n...</div></div></div>",
        "id": 190430646,
        "sender_full_name": "Alex Crichton",
        "timestamp": 1584039690
    }
]