[
    {
        "content": "<p>Any GitHub-CI wizards present who would be able to debug why <a href=\"https://github.com/bytecodealliance/wasmtime/pull/1570\" title=\"https://github.com/bytecodealliance/wasmtime/pull/1570\">https://github.com/bytecodealliance/wasmtime/pull/1570</a> has no CI tests (none pending/queued/...)? The PR doesn't change any config/metadata files, and tests are clean locally.</p>\n<div class=\"message_embed\"><a class=\"message_embed_image\" href=\"https://github.com/bytecodealliance/wasmtime/pull/1570\" style=\"background-image: url(https://avatars0.githubusercontent.com/u/54038801?s=400&amp;v=4)\"></a><div class=\"data-container\"><div class=\"message_embed_title\"><a href=\"https://github.com/bytecodealliance/wasmtime/pull/1570\" title=\"Fix long-range (non-colocated) aarch64 calls to not use Arm64Call reloc, and fix simplejit to use new long-distance call. by cfallin · Pull Request #1570 · bytecodealliance/wasmtime\">Fix long-range (non-colocated) aarch64 calls to not use Arm64Call reloc, and fix simplejit to use new long-distance call. by cfallin · Pull Request #1570 · bytecodealliance/wasmtime</a></div><div class=\"message_embed_description\">Previously, every call was lowered on AArch64 to a call instruction, which\ntakes a signed 26-bit PC-relative offset. Including the 2-bit left shift, this\ngives a range of +/- 128 MB. Longer-distanc...</div></div></div>",
        "id": 196257631,
        "sender_full_name": "Chris Fallin",
        "timestamp": 1588639855
    },
    {
        "content": "<p>The last rebase/force-push of mine didn't seem to kick the test-runner in the right way either</p>",
        "id": 196257651,
        "sender_full_name": "Chris Fallin",
        "timestamp": 1588639885
    },
    {
        "content": "<p><span class=\"user-mention\" data-user-id=\"254389\">@Chris Fallin</span> I clicked on the actions tab of the repo and it says GitHub is having issues</p>",
        "id": 196262328,
        "sender_full_name": "Alex Crichton",
        "timestamp": 1588646066
    },
    {
        "content": "<p>Typically a force.push should.retrigger but now they may just have issues</p>",
        "id": 196262351,
        "sender_full_name": "Alex Crichton",
        "timestamp": 1588646089
    },
    {
        "content": "<p>OK, thanks, will wait till their infra is back up before poking it further :-)</p>",
        "id": 196262366,
        "sender_full_name": "Chris Fallin",
        "timestamp": 1588646122
    },
    {
        "content": "<p><a href=\"https://www.githubstatus.com/incidents/ljygds069np9\" title=\"https://www.githubstatus.com/incidents/ljygds069np9\">https://www.githubstatus.com/incidents/ljygds069np9</a></p>\n<div class=\"message_embed\"><a class=\"message_embed_image\" href=\"https://www.githubstatus.com/incidents/ljygds069np9\" style=\"background-image: url(https://dka575ofm4ao0.cloudfront.net/pages-twitter_logos/original/36420/GitHub-Mark-120px-plus.png)\"></a><div class=\"data-container\"><div class=\"message_embed_title\"><a href=\"https://www.githubstatus.com/incidents/ljygds069np9\" title=\"Incident on 2020-05-05 00:45 UTC\">Incident on 2020-05-05 00:45 UTC</a></div><div class=\"message_embed_description\">GitHub's Status Page - Incident on 2020-05-05 00:45 UTC.</div></div></div>",
        "id": 196262378,
        "sender_full_name": "Alex Crichton",
        "timestamp": 1588646146
    },
    {
        "content": "<p>Something kind of odd is happening here again. I force-pushed and the resulting runs ended with a 404 in a \"download artifacts\" step; forced a re-run and now the git checkout is failing with:</p>\n<div class=\"codehilite\"><pre><span></span><code>git checkout --progress --force 692f9e4ff3379b6f1bf6dbd01fd9d7ca1ba8b921\n##[error]fatal: reference is not a tree: 692f9e4ff3379b6f1bf6dbd01fd9d7ca1ba8b921\n##[error]Git checkout failed with exit code: 128\n##[error]Exit code 1 returned from process: file name &#39;/home/runner/runners/2.169.1/bin/Runner.PluginHost&#39;, arguments &#39;action &quot;GitHub.Runner.Plugins.Repository.v1_0.CheckoutTask, Runner.Plugins&quot;&#39;.\n</code></pre></div>\n\n\n<p>(link: <a href=\"https://github.com/bytecodealliance/wasmtime/pull/1570/checks?check_run_id=646758917\" title=\"https://github.com/bytecodealliance/wasmtime/pull/1570/checks?check_run_id=646758917\">https://github.com/bytecodealliance/wasmtime/pull/1570/checks?check_run_id=646758917</a>)</p>\n<p>Disk space error? Or something else? Not sure how to debug...</p>\n<div class=\"message_embed\"><a class=\"message_embed_image\" href=\"https://github.com/bytecodealliance/wasmtime/pull/1570/checks?check_run_id=646758917\" style=\"background-image: url(https://avatars2.githubusercontent.com/u/216148?s=400&amp;v=4)\"></a><div class=\"data-container\"><div class=\"message_embed_title\"><a href=\"https://github.com/bytecodealliance/wasmtime/pull/1570/checks?check_run_id=646758917\" title=\"Fix long-range (non-colocated) aarch64 calls to not use Arm64Call reloc, and fix simplejit to use new long-distance call. by cfallin · Pull Request #1570 · bytecodealliance/wasmtime\">Fix long-range (non-colocated) aarch64 calls to not use Arm64Call reloc, and fix simplejit to use new long-distance call. by cfallin · Pull Request #1570 · bytecodealliance/wasmtime</a></div><div class=\"message_embed_description\">Previously, every call was lowered on AArch64 to a call instruction, which\ntakes a signed 26-bit PC-relative offset. Including the 2-bit left shift, this\ngives a range of +/- 128 MB. Longer-distanc...</div></div></div>",
        "id": 196332829,
        "sender_full_name": "Chris Fallin",
        "timestamp": 1588696654
    },
    {
        "content": "<p>uh...</p>",
        "id": 196334285,
        "sender_full_name": "Alex Crichton",
        "timestamp": 1588697400
    },
    {
        "content": "<p>that can happen if you restart a PR build b/c it's a bug in github actions</p>",
        "id": 196334348,
        "sender_full_name": "Alex Crichton",
        "timestamp": 1588697411
    },
    {
        "content": "<p>but this was just from a straight push?</p>",
        "id": 196334358,
        "sender_full_name": "Alex Crichton",
        "timestamp": 1588697417
    },
    {
        "content": "<p>That error came after I hit 'rerun jobs'; but the builds from the push also errored out, with a 404 while downloading aarch64 artifacts (I didn't save the logs, sorry; should have)</p>",
        "id": 196334896,
        "sender_full_name": "Chris Fallin",
        "timestamp": 1588697672
    },
    {
        "content": "<p>I'll retrigger with a push and see what happens.</p>",
        "id": 196334940,
        "sender_full_name": "Chris Fallin",
        "timestamp": 1588697693
    },
    {
        "content": "<p>I had similar 404 things, only <code>git rebase</code> worked for me &amp;&amp; <code>git push -f</code></p>",
        "id": 196335480,
        "sender_full_name": "Yury Delendik",
        "timestamp": 1588697935
    },
    {
        "content": "<p><span class=\"user-mention\" data-user-id=\"254389\">@Chris Fallin</span> oh for PRs the \"rerun jobs\" button is always busted</p>",
        "id": 196336328,
        "sender_full_name": "Alex Crichton",
        "timestamp": 1588698288
    },
    {
        "content": "<p>I dunno why, I think it's basically a bug in github actions</p>",
        "id": 196336346,
        "sender_full_name": "Alex Crichton",
        "timestamp": 1588698298
    },
    {
        "content": "<p>Good to know, thanks</p>",
        "id": 196336373,
        "sender_full_name": "Chris Fallin",
        "timestamp": 1588698305
    },
    {
        "content": "<p>for failures to download it's probably a transient error with uploads/downloads</p>",
        "id": 196336378,
        "sender_full_name": "Alex Crichton",
        "timestamp": 1588698306
    },
    {
        "content": "<p>to retrigger a PR build the only way I know is to force-push</p>",
        "id": 196336401,
        "sender_full_name": "Alex Crichton",
        "timestamp": 1588698316
    },
    {
        "content": "<p>e.g. `git commit --amend &amp;&amp; git push -f</p>",
        "id": 196336416,
        "sender_full_name": "Alex Crichton",
        "timestamp": 1588698323
    },
    {
        "content": "<p>got it; hopefully this one works :-)</p>",
        "id": 196336433,
        "sender_full_name": "Chris Fallin",
        "timestamp": 1588698334
    }
]